### ISSUE TITLE
Request from Galois: add circuit metadata

### ISSUE THREAD

**Issue by lisaoverall** [trailofbits/mcircuit#15]
First question r.e. the circuit you provided us. It looks like it's missing the metadata of # inputs and # outputs (as specified here: https://homes.esat.kuleuven.be/~nsmart/MPC/). Is that something you could augment the circuit to support?

**Comment by woodruffw** [comment]
Per that doc, there's 4 pieces of metadata we need to add:

* A line defining the number of gates and then the number of wires in the circuit.
* The number of input values niv (e.g. if doing z=a+b mod p we have niv=3, one input each for a, b and p).
    * Then niv numbers defining the number of input wires per input value: ni_1,..,ni_niv
* The number of output values nov (e.g. if doing z=a+b mod p we have nov=1, corresponding to z).
    * Then nov numbers defining the number of output wires per output value: no_1,...,no_nov

The number of gates and input values _should_ be pretty easy, since it's just the size of the gate list and witness list, respectively (assuming we read the witness values via `INPUT`).

The number of wires in the circuit is a little more annoying: we probably need to walk the gates to find the highest wire number. This suggests that we currently have the wrong abstraction.

I'm not 100% sure about the number of output values -- is that the number of things eventually sent to `OUTPUT`, or just the number of outputs of all gates?
